<?php

$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['scheduler']['tasks'][\Graphodata\GdPdfimport\Task\ImportTask::class] = [
    'extension' => 'gd_pdfimport',
    'title' => 'Run PDF Importer',
    'description' => 'Reads HTML file generated by word and creates TYPO3 pages'
];

\TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin(
    'Graphodata.GdPdfimport',
    'Pi1',
    [
        'Pdf' => 'show, data'
    ],
    [
        'Pdf' => 'show, data'
    ]
);